package log4net;import Common.Activation;import static Common.Helper.Convert;import static Common.Helper.getGetObjectName;import static Common.Helper.getReturnObjectName;import static Common.Helper.ConvertToConcreteInterfaceImplementation;import Common.Helper;import com.javonet.Javonet;
                        import com.javonet.JavonetException;
                        import com.javonet.JavonetFramework;
                        import com.javonet.api.NObject;
                        import com.javonet.api.NEnum;
                        import com.javonet.api.keywords.NRef;
                        import com.javonet.api.keywords.NOut;
                        import com.javonet.api.NControlContainer;import java.util.concurrent.atomic.AtomicReference;import log4net.*;
import jio.System.*;
import log4net.Core.*;public interface ILog extends ILoggerWrapper { public void Debug (NObject message);public void Debug (NObject message,jio.System.Exception exception);public void DebugFormat (java.lang.String format,NObject[] args);public void DebugFormat (java.lang.String format,NObject arg0);public void DebugFormat (java.lang.String format,NObject arg0,NObject arg1);public void DebugFormat (java.lang.String format,NObject arg0,NObject arg1,NObject arg2);public void DebugFormat (IFormatProvider provider,java.lang.String format,NObject[] args);public void Info (NObject message);public void Info (NObject message,jio.System.Exception exception);public void InfoFormat (java.lang.String format,NObject[] args);public void InfoFormat (java.lang.String format,NObject arg0);public void InfoFormat (java.lang.String format,NObject arg0,NObject arg1);public void InfoFormat (java.lang.String format,NObject arg0,NObject arg1,NObject arg2);public void InfoFormat (IFormatProvider provider,java.lang.String format,NObject[] args);public void Warn (NObject message);public void Warn (NObject message,jio.System.Exception exception);public void WarnFormat (java.lang.String format,NObject[] args);public void WarnFormat (java.lang.String format,NObject arg0);public void WarnFormat (java.lang.String format,NObject arg0,NObject arg1);public void WarnFormat (java.lang.String format,NObject arg0,NObject arg1,NObject arg2);public void WarnFormat (IFormatProvider provider,java.lang.String format,NObject[] args);public void Error (NObject message);public void Error (NObject message,jio.System.Exception exception);public void ErrorFormat (java.lang.String format,NObject[] args);public void ErrorFormat (java.lang.String format,NObject arg0);public void ErrorFormat (java.lang.String format,NObject arg0,NObject arg1);public void ErrorFormat (java.lang.String format,NObject arg0,NObject arg1,NObject arg2);public void ErrorFormat (IFormatProvider provider,java.lang.String format,NObject[] args);public void Fatal (NObject message);public void Fatal (NObject message,jio.System.Exception exception);public void FatalFormat (java.lang.String format,NObject[] args);public void FatalFormat (java.lang.String format,NObject arg0);public void FatalFormat (java.lang.String format,NObject arg0,NObject arg1);public void FatalFormat (java.lang.String format,NObject arg0,NObject arg1,NObject arg2);public void FatalFormat (IFormatProvider provider,java.lang.String format,NObject[] args);}